// ===== SKILLVERSE DATA =====

const DOMAINS = [
    { id: 'cloud', name: 'Cloud Computing', icon: '☁️', color: '#4285F4' },
    { id: 'data-science', name: 'Data Science', icon: '📊', color: '#10B981' },
    { id: 'ai-ml', name: 'AI & ML', icon: '🤖', color: '#A855F7' },
    { id: 'cybersecurity', name: 'Cybersecurity', icon: '🛡️', color: '#EF4444' },
    { id: 'web-dev', name: 'Web Development', icon: '🌐', color: '#06B6D4' },
    { id: 'digital-marketing', name: 'Digital Marketing', icon: '📈', color: '#F59E0B' },
    { id: 'devops', name: 'DevOps', icon: '⚙️', color: '#6366F1' },
    { id: 'database', name: 'Database', icon: '🗄️', color: '#EC4899' },
    { id: 'networking', name: 'Networking', icon: '🔗', color: '#14B8A6' },
    { id: 'project-mgmt', name: 'Project Management', icon: '📋', color: '#8B5CF6' },
    { id: 'design', name: 'UI/UX Design', icon: '🎨', color: '#F97316' },
    { id: 'blockchain', name: 'Blockchain', icon: '⛓️', color: '#3B82F6' },
    // Non-Technical Domains
    { id: 'business', name: 'Business & Management', icon: '💼', color: '#F59E0B', category: 'non-tech' },
    { id: 'marketing-media', name: 'Marketing & Media', icon: '📢', color: '#EF4444', category: 'non-tech' },
    { id: 'creative-design', name: 'Creative & Design', icon: '🎨', color: '#EC4899', category: 'non-tech' },
    { id: 'social-humanities', name: 'Social & Humanities', icon: '🌍', color: '#10B981', category: 'non-tech' },
    { id: 'commerce-finance', name: 'Commerce & Finance', icon: '💰', color: '#8B5CF6', category: 'non-tech' },
    { id: 'hospitality-travel', name: 'Hospitality & Travel', icon: '✈️', color: '#06B6D4', category: 'non-tech' },
    { id: 'law', name: 'Law', icon: '⚖️', color: '#374151', category: 'non-tech' },
];

const COMPANIES = [
    { id: 'google', name: 'Google', icon: 'fab fa-google', color: '#4285F4', bg: 'rgba(66,133,244,0.15)', desc: 'Access free courses from Google on Cloud, AI, Data Analytics, and Digital Marketing with professional certificates.', url: 'https://grow.google/certificates/' },
    { id: 'microsoft', name: 'Microsoft', icon: 'fab fa-microsoft', color: '#0078D7', bg: 'rgba(0,120,215,0.15)', desc: 'Microsoft Learn offers free, interactive training paths with certifications across Azure, Power Platform, and more.', url: 'https://learn.microsoft.com/' },
    { id: 'aws', name: 'Amazon AWS', icon: 'fab fa-aws', color: '#FF9900', bg: 'rgba(255,153,0,0.15)', desc: 'AWS Training provides free digital courses, labs, and certification prep for cloud computing professionals.', url: 'https://aws.amazon.com/training/' },
    { id: 'ibm', name: 'IBM', icon: 'fab fa-ibm', color: '#1F70C1', bg: 'rgba(31,112,193,0.15)', desc: 'IBM SkillsBuild offers free courses in AI, cybersecurity, data science, and cloud with digital credentials.', url: 'https://skillsbuild.org/' },
    { id: 'meta', name: 'Meta', icon: 'fab fa-meta', color: '#1877F2', bg: 'rgba(24,119,242,0.15)', desc: 'Meta Blueprint provides free marketing courses and certifications for Facebook, Instagram, and WhatsApp.', url: 'https://www.facebook.com/business/learn' },
    { id: 'cisco', name: 'Cisco', icon: 'fab fa-cisco', color: '#1BA0D7', bg: 'rgba(27,160,215,0.15)', desc: 'Cisco Networking Academy offers free courses in networking, cybersecurity, and IoT with industry certifications.', url: 'https://www.netacad.com/' },
    { id: 'oracle', name: 'Oracle', icon: 'fas fa-database', color: '#F80000', bg: 'rgba(248,0,0,0.12)', desc: 'Oracle University provides free learning paths for database, cloud infrastructure, and Java development.', url: 'https://education.oracle.com/' },
    { id: 'salesforce', name: 'Salesforce', icon: 'fas fa-cloud', color: '#00A1E0', bg: 'rgba(0,161,224,0.15)', desc: 'Salesforce Trailhead offers free, gamified learning paths for CRM, development, and business skills.', url: 'https://trailhead.salesforce.com/' },
    { id: 'hubspot', name: 'HubSpot', icon: 'fab fa-hubspot', color: '#FF7A59', bg: 'rgba(255,122,89,0.15)', desc: 'HubSpot Academy provides free certification courses in inbound marketing, sales, and customer service.', url: 'https://academy.hubspot.com/' },
    { id: 'linkedin', name: 'LinkedIn', icon: 'fab fa-linkedin', color: '#0A66C2', bg: 'rgba(10,102,194,0.15)', desc: 'LinkedIn Learning offers select free courses in business, technology, and creative skills.', url: 'https://www.linkedin.com/learning/' },
    { id: 'fortinet', name: 'Fortinet', icon: 'fas fa-shield-halved', color: '#EE3124', bg: 'rgba(238,49,36,0.12)', desc: 'Fortinet Training Institute offers free cybersecurity courses and NSE certifications for all skill levels.', url: 'https://training.fortinet.com/' },
    { id: 'github', name: 'GitHub', icon: 'fab fa-github', color: '#F0F0F5', bg: 'rgba(240,240,245,0.1)', desc: 'GitHub Skills provides free interactive courses to master Git, GitHub Actions, and collaborative development.', url: 'https://skills.github.com/' },
];

const COURSES = [
    // Google Courses
    { id: 1, title: 'Google Cloud Computing Foundations', company: 'google', domain: 'cloud', level: 'Beginner', duration: '20 hours', rating: 4.8, tags: ['GCP', 'Cloud', 'Infrastructure'], desc: 'Learn cloud computing concepts, Google Cloud products, and how to create and manage cloud resources. Earn a certificate of completion.', url: 'https://www.cloudskillsboost.google/paths', featured: true },
    { id: 2, title: 'Google Data Analytics Professional Certificate', company: 'google', domain: 'data-science', level: 'Beginner', duration: '24 hours', rating: 4.7, tags: ['Data Analytics', 'SQL', 'Spreadsheets'], desc: 'Prepare for a career in data analytics with hands-on projects. Learn data cleaning, analysis, visualization, and R programming.', url: 'https://grow.google/certificates/data-analytics/', featured: true },
    { id: 3, title: 'Google AI Essentials', company: 'google', domain: 'ai-ml', level: 'Beginner', duration: '10 hours', rating: 4.9, tags: ['AI', 'Machine Learning', 'Generative AI'], desc: 'Learn the fundamentals of AI, including how AI works, responsible AI, and how to use AI tools effectively in your work.', url: 'https://grow.google/certificates/', featured: true },
    { id: 4, title: 'Google Digital Marketing & E-commerce', company: 'google', domain: 'digital-marketing', level: 'Beginner', duration: '20 hours', rating: 4.6, tags: ['SEO', 'SEM', 'Analytics'], desc: 'Master the skills needed for an entry-level digital marketing role including SEO, SEM, email marketing, and analytics.', url: 'https://grow.google/certificates/digital-marketing-ecommerce/', featured: false },
    { id: 5, title: 'Google UX Design Professional Certificate', company: 'google', domain: 'design', level: 'Beginner', duration: '24 hours', rating: 4.8, tags: ['UX', 'UI', 'Figma', 'Prototyping'], desc: 'Design user experiences for mobile apps and websites. Learn the UX design process, wireframing, prototyping, and usability testing.', url: 'https://grow.google/certificates/ux-design/', featured: true },

    // Microsoft Courses
    { id: 6, title: 'Microsoft Azure Fundamentals (AZ-900)', company: 'microsoft', domain: 'cloud', level: 'Beginner', duration: '15 hours', rating: 4.7, tags: ['Azure', 'Cloud', 'Fundamentals'], desc: 'Master Azure cloud concepts, services, security, privacy, and pricing. Free preparation for the AZ-900 certification exam.', url: 'https://learn.microsoft.com/en-us/training/paths/az-900-describe-cloud-concepts/', featured: true },
    { id: 7, title: 'Microsoft AI Fundamentals (AI-900)', company: 'microsoft', domain: 'ai-ml', level: 'Beginner', duration: '12 hours', rating: 4.6, tags: ['AI', 'Azure AI', 'Cognitive Services'], desc: 'Learn AI workloads, machine learning on Azure, computer vision, NLP, and conversational AI fundamentals.', url: 'https://learn.microsoft.com/en-us/training/paths/get-started-with-artificial-intelligence-on-azure/', featured: false },
    { id: 8, title: 'Microsoft Power Platform Fundamentals', company: 'microsoft', domain: 'devops', level: 'Beginner', duration: '10 hours', rating: 4.5, tags: ['Power Apps', 'Power Automate', 'Low Code'], desc: 'Learn to build apps, automate workflows, and analyze data with Microsoft Power Platform — no coding required.', url: 'https://learn.microsoft.com/en-us/training/paths/power-plat-fundamentals/', featured: false },
    { id: 9, title: 'Microsoft Security Fundamentals (SC-900)', company: 'microsoft', domain: 'cybersecurity', level: 'Beginner', duration: '14 hours', rating: 4.7, tags: ['Security', 'Compliance', 'Identity'], desc: 'Understand security, compliance, and identity concepts in cloud-based and related Microsoft services.', url: 'https://learn.microsoft.com/en-us/training/paths/describe-concepts-of-security-compliance-identity/', featured: true },
    { id: 10, title: 'Microsoft Data Fundamentals (DP-900)', company: 'microsoft', domain: 'database', level: 'Beginner', duration: '12 hours', rating: 4.5, tags: ['SQL', 'Azure Data', 'Analytics'], desc: 'Learn core data concepts and Azure data services including relational, non-relational, and analytics workloads.', url: 'https://learn.microsoft.com/en-us/training/paths/azure-data-fundamentals-explore-core-data-concepts/', featured: false },

    // AWS Courses
    { id: 11, title: 'AWS Cloud Practitioner Essentials', company: 'aws', domain: 'cloud', level: 'Beginner', duration: '8 hours', rating: 4.8, tags: ['AWS', 'Cloud', 'Certification Prep'], desc: 'Build overall understanding of the AWS Cloud including core services, security, architecture, pricing, and support.', url: 'https://aws.amazon.com/training/learn-about/cloud-practitioner/', featured: true },
    { id: 12, title: 'AWS Machine Learning Foundations', company: 'aws', domain: 'ai-ml', level: 'Intermediate', duration: '16 hours', rating: 4.6, tags: ['ML', 'SageMaker', 'Deep Learning'], desc: 'Learn machine learning concepts, AWS ML services, and how to build, train, and deploy ML models using SageMaker.', url: 'https://aws.amazon.com/training/learn-about/machine-learning/', featured: false },
    { id: 13, title: 'AWS Solutions Architect Learning Path', company: 'aws', domain: 'cloud', level: 'Intermediate', duration: '30 hours', rating: 4.7, tags: ['Architecture', 'AWS', 'Solutions Design'], desc: 'Deep dive into designing distributed systems on AWS, covering compute, storage, networking, and database services.', url: 'https://aws.amazon.com/training/', featured: false },
    { id: 14, title: 'AWS Security Fundamentals', company: 'aws', domain: 'cybersecurity', level: 'Beginner', duration: '6 hours', rating: 4.5, tags: ['AWS Security', 'IAM', 'Compliance'], desc: 'Learn AWS security concepts including identity, detective controls, infrastructure protection, and data protection.', url: 'https://aws.amazon.com/training/', featured: false },

    // IBM Courses
    { id: 15, title: 'IBM Data Science Professional Certificate', company: 'ibm', domain: 'data-science', level: 'Beginner', duration: '20 hours', rating: 4.6, tags: ['Python', 'SQL', 'Data Visualization'], desc: 'Master data science with hands-on projects. Learn Python, SQL, data analysis, machine learning, and data visualization.', url: 'https://skillsbuild.org/', featured: true },
    { id: 16, title: 'IBM Cybersecurity Analyst', company: 'ibm', domain: 'cybersecurity', level: 'Beginner', duration: '18 hours', rating: 4.5, tags: ['Threat Intelligence', 'SIEM', 'Incident Response'], desc: 'Develop skills in cybersecurity analytics including threat intelligence, network security, and incident response.', url: 'https://skillsbuild.org/', featured: false },
    { id: 17, title: 'IBM AI Engineering Professional Certificate', company: 'ibm', domain: 'ai-ml', level: 'Intermediate', duration: '25 hours', rating: 4.7, tags: ['Deep Learning', 'TensorFlow', 'Keras'], desc: 'Build and deploy AI models using machine learning and deep learning techniques with TensorFlow and Keras.', url: 'https://skillsbuild.org/', featured: false },
    { id: 18, title: 'IBM Full Stack Cloud Developer', company: 'ibm', domain: 'web-dev', level: 'Intermediate', duration: '22 hours', rating: 4.5, tags: ['React', 'Node.js', 'Cloud Native'], desc: 'Learn full stack web development with React, Node.js, Python, and cloud-native tools for building scalable applications.', url: 'https://skillsbuild.org/', featured: false },

    // Meta Courses
    { id: 19, title: 'Meta Social Media Marketing', company: 'meta', domain: 'digital-marketing', level: 'Beginner', duration: '16 hours', rating: 4.6, tags: ['Social Media', 'Facebook Ads', 'Instagram'], desc: 'Learn to create and manage social media marketing campaigns on Facebook, Instagram, and WhatsApp Business.', url: 'https://www.facebook.com/business/learn', featured: true },
    { id: 20, title: 'Meta Front-End Developer Certificate', company: 'meta', domain: 'web-dev', level: 'Beginner', duration: '28 hours', rating: 4.7, tags: ['React', 'JavaScript', 'CSS'], desc: 'Build a career as a front-end developer. Learn HTML, CSS, JavaScript, React, and version control with Git.', url: 'https://www.facebook.com/business/learn', featured: true },
    { id: 21, title: 'Meta Database Engineer Certificate', company: 'meta', domain: 'database', level: 'Intermediate', duration: '22 hours', rating: 4.5, tags: ['MySQL', 'Python', 'Database Design'], desc: 'Master database engineering with MySQL, Python, and data modeling. Learn to design and manage scalable databases.', url: 'https://www.facebook.com/business/learn', featured: false },

    // Cisco Courses
    { id: 22, title: 'Cisco Networking Essentials', company: 'cisco', domain: 'networking', level: 'Beginner', duration: '30 hours', rating: 4.7, tags: ['Networking', 'TCP/IP', 'Routing'], desc: 'Learn computer networking fundamentals including network types, protocols, IP addressing, and basic security.', url: 'https://www.netacad.com/', featured: true },
    { id: 23, title: 'Cisco Introduction to Cybersecurity', company: 'cisco', domain: 'cybersecurity', level: 'Beginner', duration: '6 hours', rating: 4.6, tags: ['Cybersecurity', 'Threats', 'Network Security'], desc: 'Explore the world of cybersecurity. Learn about common threats, attack types, and how to protect personal and organizational data.', url: 'https://www.netacad.com/', featured: false },
    { id: 24, title: 'Cisco Introduction to IoT', company: 'cisco', domain: 'networking', level: 'Beginner', duration: '8 hours', rating: 4.4, tags: ['IoT', 'Sensors', 'Automation'], desc: 'Discover how Internet of Things transforms industries. Learn about IoT devices, connectivity, data analytics, and security.', url: 'https://www.netacad.com/', featured: false },

    // Oracle Courses
    { id: 25, title: 'Oracle Database Foundations', company: 'oracle', domain: 'database', level: 'Beginner', duration: '20 hours', rating: 4.5, tags: ['Oracle DB', 'SQL', 'PL/SQL'], desc: 'Learn database fundamentals with Oracle. Cover relational database concepts, SQL queries, and data management.', url: 'https://education.oracle.com/', featured: false },
    { id: 26, title: 'Oracle Cloud Infrastructure Foundations', company: 'oracle', domain: 'cloud', level: 'Beginner', duration: '14 hours', rating: 4.4, tags: ['OCI', 'Cloud', 'Infrastructure'], desc: 'Get started with Oracle Cloud Infrastructure. Learn about cloud concepts, core services, and security.', url: 'https://education.oracle.com/', featured: false },

    // Salesforce Courses
    { id: 27, title: 'Salesforce Administrator Certification Prep', company: 'salesforce', domain: 'project-mgmt', level: 'Beginner', duration: '25 hours', rating: 4.7, tags: ['CRM', 'Salesforce', 'Admin'], desc: 'Prepare for the Salesforce Admin certification with hands-on trails covering CRM setup, automation, and reporting.', url: 'https://trailhead.salesforce.com/', featured: true },
    { id: 28, title: 'Salesforce Platform Developer', company: 'salesforce', domain: 'web-dev', level: 'Intermediate', duration: '30 hours', rating: 4.6, tags: ['Apex', 'Lightning', 'Salesforce Dev'], desc: 'Learn Salesforce development with Apex programming, Lightning Web Components, and platform best practices.', url: 'https://trailhead.salesforce.com/', featured: false },

    // HubSpot Courses
    { id: 29, title: 'HubSpot Inbound Marketing Certification', company: 'hubspot', domain: 'digital-marketing', level: 'Beginner', duration: '5 hours', rating: 4.8, tags: ['Inbound Marketing', 'Content Strategy', 'SEO'], desc: 'Master inbound marketing methodology including content marketing, social media, email marketing, and lead nurturing.', url: 'https://academy.hubspot.com/', featured: true },
    { id: 30, title: 'HubSpot Content Marketing Certification', company: 'hubspot', domain: 'digital-marketing', level: 'Beginner', duration: '6 hours', rating: 4.7, tags: ['Content', 'Blogging', 'Strategy'], desc: 'Learn to create a content marketing strategy, build a blog, and promote content effectively.', url: 'https://academy.hubspot.com/', featured: false },
    { id: 31, title: 'HubSpot Email Marketing Certification', company: 'hubspot', domain: 'digital-marketing', level: 'Beginner', duration: '4 hours', rating: 4.6, tags: ['Email', 'Automation', 'Lead Gen'], desc: 'Design, optimize, and automate email marketing campaigns that engage and convert customers.', url: 'https://academy.hubspot.com/', featured: false },

    // LinkedIn Courses
    { id: 32, title: 'LinkedIn Project Management Foundations', company: 'linkedin', domain: 'project-mgmt', level: 'Beginner', duration: '8 hours', rating: 4.5, tags: ['Project Management', 'Agile', 'Planning'], desc: 'Learn project management fundamentals including project planning, execution, monitoring, and agile methodologies.', url: 'https://www.linkedin.com/learning/', featured: false },

    // Fortinet Courses
    { id: 33, title: 'Fortinet NSE 1 - Information Security Awareness', company: 'fortinet', domain: 'cybersecurity', level: 'Beginner', duration: '3 hours', rating: 4.6, tags: ['Security Awareness', 'Threats', 'Best Practices'], desc: 'Understand the cyber threat landscape, types of threat actors, and social engineering techniques. Build security awareness.', url: 'https://training.fortinet.com/', featured: true },
    { id: 34, title: 'Fortinet NSE 2 - Network Security Fundamentals', company: 'fortinet', domain: 'cybersecurity', level: 'Beginner', duration: '5 hours', rating: 4.5, tags: ['Firewall', 'Endpoint Security', 'SIEM'], desc: 'Learn about firewalls, endpoint security, access control, and SIEM solutions for modern network security.', url: 'https://training.fortinet.com/', featured: false },
    { id: 35, title: 'Fortinet NSE 3 - Network Security Advanced', company: 'fortinet', domain: 'cybersecurity', level: 'Intermediate', duration: '8 hours', rating: 4.4, tags: ['FortiGate', 'Security Fabric', 'Advanced Threats'], desc: 'Dive deeper into Fortinet security solutions including FortiGate, FortiWeb, SD-WAN, and the Fortinet Security Fabric.', url: 'https://training.fortinet.com/', featured: false },

    // GitHub Courses
    { id: 36, title: 'GitHub Foundations Certification', company: 'github', domain: 'devops', level: 'Beginner', duration: '10 hours', rating: 4.8, tags: ['Git', 'GitHub', 'Version Control'], desc: 'Master Git and GitHub fundamentals including repositories, branches, commits, pull requests, and GitHub Actions.', url: 'https://skills.github.com/', featured: true },
    { id: 37, title: 'GitHub Actions for CI/CD', company: 'github', domain: 'devops', level: 'Intermediate', duration: '8 hours', rating: 4.6, tags: ['CI/CD', 'Automation', 'GitHub Actions'], desc: 'Learn to automate your software development workflows with GitHub Actions for continuous integration and deployment.', url: 'https://skills.github.com/', featured: false },

    // Additional variety courses
    { id: 38, title: 'Google Project Management Certificate', company: 'google', domain: 'project-mgmt', level: 'Beginner', duration: '20 hours', rating: 4.7, tags: ['Agile', 'Scrum', 'Project Planning'], desc: 'Gain the skills needed for an entry-level project management role. Learn agile project management and Scrum methodology.', url: 'https://grow.google/certificates/project-management/', featured: false },
    { id: 39, title: 'IBM Blockchain Essentials', company: 'ibm', domain: 'blockchain', level: 'Beginner', duration: '8 hours', rating: 4.4, tags: ['Blockchain', 'Hyperledger', 'Smart Contracts'], desc: 'Understand blockchain technology fundamentals, distributed ledgers, smart contracts, and real-world use cases.', url: 'https://skillsbuild.org/', featured: false },
    { id: 40, title: 'AWS DevOps Engineering', company: 'aws', domain: 'devops', level: 'Advanced', duration: '35 hours', rating: 4.7, tags: ['DevOps', 'CI/CD', 'Infrastructure as Code'], desc: 'Advanced DevOps practices on AWS including CI/CD pipelines, infrastructure as code, monitoring, and incident response.', url: 'https://aws.amazon.com/training/', featured: false },

    // Business & Management
    { id: 41, title: 'BBA: Foundations of Business Strategy', company: 'google', domain: 'business', level: 'Beginner', duration: '12 hours', rating: 4.8, tags: ['BBA', 'Strategy', 'Management'], desc: 'Learn the core concepts of business administration and strategic planning used by top consulting firms.', url: 'https://grow.google/certificates/', featured: true },
    { id: 42, title: 'Management Studies (BMS) Essentials', company: 'linkedin', domain: 'business', level: 'Beginner', duration: '8 hours', rating: 4.6, tags: ['BMS', 'Leadership', 'Management'], desc: 'Master the fundamentals of organizational behavior and management studies for early-career professionals.', url: 'https://www.linkedin.com/learning/', featured: false },
    { id: 43, title: 'Business Management (BBM) Leadership', company: 'microsoft', domain: 'business', level: 'Intermediate', duration: '15 hours', rating: 4.7, tags: ['BBM', 'Operations', 'Finance'], desc: 'Comprehensive guide to business management, covering operations, human resources, and financial oversight.', url: 'https://learn.microsoft.com/', featured: false },

    // Marketing & Media
    { id: 44, title: 'BBA Digital Marketing Specialization', company: 'meta', domain: 'marketing-media', level: 'Beginner', duration: '20 hours', rating: 4.9, tags: ['Digital Marketing', 'BBA', 'Ads'], desc: 'Learn modern digital marketing strategies, from social media management to data-driven advertising on Meta platforms.', url: 'https://www.facebook.com/business/learn', featured: true },
    { id: 45, title: 'Journalism & Mass Communication Foundations', company: 'google', domain: 'marketing-media', level: 'Beginner', duration: '10 hours', rating: 4.5, tags: ['Media', 'Writing', 'Communication'], desc: 'Explore the basics of modern journalism, digital media ethics, and effective mass communication in the internet age.', url: 'https://grow.google/certificates/', featured: false },
    { id: 46, title: 'Advertising & Public Relations Masterclass', company: 'hubspot', domain: 'marketing-media', level: 'Intermediate', duration: '12 hours', rating: 4.7, tags: ['PR', 'Advertising', 'Branding'], desc: 'Master the art of brand storytelling, PR crisis management, and strategic advertising campaigns.', url: 'https://academy.hubspot.com/', featured: false },

    // Creative & Design
    { id: 47, title: 'Bachelor of Fine Arts (BFA): Visual Arts', company: 'linkedin', domain: 'creative-design', level: 'Beginner', duration: '18 hours', rating: 4.6, tags: ['BFA', 'Art', 'Visuals'], desc: 'Develop your artistic voice through fundamental techniques in drawing, painting, and digital composition.', url: 'https://www.linkedin.com/learning/', featured: false },
    { id: 48, title: 'Fashion Designing: Trend & Textile', company: 'meta', domain: 'creative-design', level: 'Beginner', duration: '14 hours', rating: 4.8, tags: ['Fashion', 'Style', 'Design'], desc: 'Learn how to identify trends, work with different textiles, and create your first fashion collection.', url: 'https://www.facebook.com/business/learn', featured: true },
    { id: 49, title: 'Interior Designing: Space & Form', company: 'google', domain: 'creative-design', level: 'Intermediate', duration: '20 hours', rating: 4.7, tags: ['Interior', 'CAD', 'Architecture'], desc: 'Master spatial planning, color theory, and modern interior design principles for residential and commercial spaces.', url: 'https://grow.google/certificates/', featured: false },

    // Social & Humanities
    { id: 50, title: 'BA Psychology: Human Behavior', company: 'ibm', domain: 'social-humanities', level: 'Beginner', duration: '25 hours', rating: 4.9, tags: ['Psychology', 'Behavior', 'Mind'], desc: 'Introduction to psychological principles, human cognition, and behavioral patterns in social environments.', url: 'https://skillsbuild.org/', featured: true },
    { id: 51, title: 'BA Sociology: Contemporary Society', company: 'meta', domain: 'social-humanities', level: 'Beginner', duration: '15 hours', rating: 4.5, tags: ['Sociology', 'Culture', 'Institutions'], desc: 'Study the structure of society, social interactions, and the impact of digital media on modern community dynamics.', url: 'https://www.facebook.com/business/learn', featured: false },
    { id: 52, title: 'Political Science & International Relations', company: 'linkedin', domain: 'social-humanities', level: 'Intermediate', duration: '12 hours', rating: 4.6, tags: ['Politics', 'IR', 'Policy'], desc: 'Gain insights into global political systems, international relations, and public policy making.', url: 'https://www.linkedin.com/learning/', featured: false },
    { id: 53, title: 'History of Global Civilizations', company: 'google', domain: 'social-humanities', level: 'Beginner', duration: '30 hours', rating: 4.7, tags: ['History', 'Culture', 'Heritage'], desc: 'A deep dive into the major historical events that shaped our modern world across different continents.', url: 'https://grow.google/certificates/', featured: false },

    // Commerce & Finance
    { id: 54, title: 'B.Com (General): Business Accounting', company: 'oracle', domain: 'commerce-finance', level: 'Beginner', duration: '22 hours', rating: 4.8, tags: ['Commerce', 'Accounting', 'Business'], desc: 'Learn fundamental accounting principles, ledger management, and financial reporting for modern businesses.', url: 'https://education.oracle.com/', featured: true },
    { id: 55, title: 'Accounting & Finance Specialization', company: 'linkedin', domain: 'commerce-finance', level: 'Intermediate', duration: '30 hours', rating: 4.7, tags: ['A&F', 'Audit', 'Finance'], desc: 'Advanced topics in corporate finance, auditing, and complex financial analysis for B.Com A&F students.', url: 'https://www.linkedin.com/learning/', featured: false },
    { id: 56, title: 'Banking & Insurance Fundamentals', company: 'salesforce', domain: 'commerce-finance', level: 'Beginner', duration: '12 hours', rating: 4.6, tags: ['Banking', 'Insurance', 'CRM'], desc: 'Understand the banking ecosystem, insurance products, and customer relationship management in finance.', url: 'https://trailhead.salesforce.com/', featured: false },

    // Hospitality & Travel
    { id: 57, title: 'Hotel Management Operations', company: 'linkedin', domain: 'hospitality-travel', level: 'Beginner', duration: '25 hours', rating: 4.8, tags: ['Hospitality', 'Hotels', 'Service'], desc: 'Practical skills for managing high-end hotel operations, guest relations, and service excellence.', url: 'https://www.linkedin.com/learning/', featured: true },
    { id: 58, title: 'Travel & Tourism Management', company: 'meta', domain: 'hospitality-travel', level: 'Beginner', duration: '15 hours', rating: 4.6, tags: ['Travel', 'Tourism', 'Agencies'], desc: 'Learn to build and market travel packages, manage tourism agencies, and understand global travel trends.', url: 'https://www.facebook.com/business/learn', featured: false },
    { id: 59, title: 'Event Management Masterclass', company: 'hubspot', domain: 'hospitality-travel', level: 'Intermediate', duration: '10 hours', rating: 4.7, tags: ['Events', 'Planning', 'Coordination'], desc: 'The ultimate guide to planning and executing successful corporate events, weddings, and conferences.', url: 'https://academy.hubspot.com/', featured: false },

    // Law
    { id: 60, title: 'Introduction to BA LLB Legal Systems', company: 'google', domain: 'law', level: 'Beginner', duration: '20 hours', rating: 4.9, tags: ['Law', 'Legal', 'Ethics'], desc: 'Foundational course on constitutional law, civil rights, and the ethical frameworks of modern legal systems.', url: 'https://grow.google/certificates/', featured: true },
    { id: 61, title: 'BBA LLB: Corporate & Business Law', company: 'ibm', domain: 'law', level: 'Intermediate', duration: '25 hours', rating: 4.7, tags: ['Corporate Law', 'Business', 'Legal'], desc: 'Specialized study of corporate legal structures, mergers, acquisitions, and business contract law.', url: 'https://skillsbuild.org/', featured: false },
];
